title: "ay2425s2-cs2103t-t09-3"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

baseUrl: "/tp"
repository: "AY2425S2-CS2103T-T09-3/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
